config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get  'pages/terms'
  get  'pages/question'
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, presence: true
    validates :content, presence: true
    validates :title, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def terms
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy] 

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def correct_user
      @post = Post.find(params[:id])
      unless @post.user == current_user
        redirect_to root_path, notice: "No access"
      end
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def current_user?(user)
    #     user == current_user
    # end
    
    # def current_user
    #     if(user_id = session[:user_id])
    #       @current_user ||= User.find_by(id: user_id)
    #     end
    # end
    
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
    <%= link_to "CryptoDiscuz", root_path, :class => "navbar-brand" %>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to 'Terms', pages_terms_path, :class => "navbar-text mr-2" %>
            <% if current_user %>
                <%= current_user.email %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "ml-3 btn btn-outline-secondary" %>
            <% else %>
                <%= link_to 'Sign up', new_user_registration_path, :class => "btn btn-outline-secondary" %>
                <%= link_to 'Log in', new_user_session_path, :class => "btn btn-outline-secondary" %>
            <% end %>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptodiscuz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'layouts/navbar' %>

<div>
    <div class="d-flex align-items-center justify-content-around mt-5 ml-1 mr-1 mb-5">
        <div>
            <h1> Connect with the best minds in crypto. </h1>
        </div>
        <div>
            <%= image_tag "flame-success-1.png", size: "300x300" %> 
        </div>
    </div>
</div>
<div class="container text-center mt-5">
    <%= link_to 'Ask a question', new_post_path, :class => "btn btn-outline-primary" %>
    <%= link_to 'View all questions', posts_path, :class => "btn btn-outline-primary" %>
</div>

app/views/pages/question.html.erb
<%= render 'layouts/navbar' %>

<% if current_user %>
    Post a question
<% else %>
    <div class="container text-center mt-5">
        Please sign up or log in to post a question! <br>
        <%= link_to 'Sign up', new_user_registration_path, :class => "mt-3 mr-3 btn btn-outline-secondary" %>
    <%= link_to 'Sign in', new_user_session_path, :class => "mt-3 btn btn-outline-secondary" %>
    </div>
    
<% end %>

app/views/pages/terms.html.erb
<%= render 'layouts/navbar' %>

<div class="container mb-5">
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Address</h5>
            <p class="card-text">In digital currency, an address is basically a destination where a user sends and receives digital currency. In a way, it is similar to a bank account.[1] These addressses usually include a long series of letters and numbers.</p>
        </div>
    </div>
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Altcoin</h5>
            <p class="card-text">An altcoin is a digital currency other than bitcoin. There were more than 1,000 altcoins listed on data source CoinMarketCap at the time of this writing. Another way of describing the term "altcoin" is referring to it as an alternative protocol asset, meaning that it follows a protocol (set of rules) that's different than that of bitcoin.</p>
        </div>
    </div>
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Arbitrage</h5>
            <p class="card-text">In crypto, arbitrage refers to taking advantage of the price difference between two different exchanges. If bitcoin is selling for £8,950 on one exchange and £9,000 on another, a trader can buy the digital currency on the first exchange and sell it on the second for a modest profit.</p>
        </div>
    </div>
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Bear/Bearish</h5>
            <p class="card-text">"Bears" believe that an asset, for example a digital currency, will decline in value. Another way of putting this is that if a trader thinks a cryptocurrency will depreciate, their sentiment surrounding the digital asset is "bearish." In many situations, traders will make use of this expectation by taking a short position on an asset, meaning that they will make a wager that will pay off should the asset in question fall in value.</p>
        </div>
    </div>
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Blocks</h5>
            <p class="card-text">Many digital currencies make use of blocks, which contain transactions that have been confirmed and then combined together.</p>
        </div>
    </div>
    <div class="card mt-5">
        <div class="card-body">
            <h5 class="card-title">Blockchain</h5>
            <p class="card-text">The blockchain, which is a distributed ledger system, consists of a series of blocks. These blocks contain verified transactions. The blockchain was designed to be not only decentralised, but also immutable, meaning that entries could not be erased once placed on this distributed ledger. The idea of the blockchain was first introduced when the bitcoin white paper was released in late 2008.[3]</p>
        </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Posted by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user == post.user %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% if current_user %>
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
<% else %>
    <div class="container text-center mt-5">
        Please sign up or log in to post a question! <br>
        <%= link_to 'Sign up', new_user_registration_path, :class => "mt-3 mr-3 btn btn-outline-secondary" %>
    <%= link_to 'Sign in', new_user_session_path, :class => "mt-3 btn btn-outline-secondary" %>
    </div>
    
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<% if current_user == @post.user %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>